apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: intelligent-backoffice-api
  namespace: intelligent-backoffice
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: intelligent-backoffice-api
